parte 3 Repository con map
AlessandroBarrionuevo/SpringBootTp pull request #3
Opened 2022-01-27 04:25 UTC by AlessandroBarrionuevo

parte 3 persistencia de datos en memoria. Crud de Sims.

2022-01-29 20:53 UTC, JhLedesma requested changes

2022-01-29 20:53 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/repository/SimRepo.java
> +    }
Aca nunca me entero en los logs si se guardo

2022-01-29 20:53 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +            return null;
Implementar excepcion en vez de retornar null

2022-01-29 20:53 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        }
Implementar excepcion en vez de retornar null

2022-01-29 20:53 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        }
Implementar excepcion en vez de retornar null

2022-01-29 20:53 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +            return null;
Implementar excepcion en vez de retornar null

2022-01-29 20:53 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/controller/SimController.java
> +    public ResponseEntity<List<Sim>> getAllSims(){
Ni get ni el get all esta trayendo la fecha de cumpleaños cuando le pegas al endpoiint. Sumado a eso, manejar fechas con el formato LocalDate

[Manejo de fechas]https://www.campusmvp.es/recursos/post/como-manejar-correctamente-fechas-en-java-el-paquete-java-time.aspx

2022-01-31 07:53 UTC, AlessandroBarrionuevo commented on src/main/java/com/spring/com/tp/services/SimService.java
> +            return null;
Se utilizo el siguiente video https://www.youtube.com/watch?v=uYoQV_AcwR4&t=1068s para incorporar excepciones.

2022-02-03 00:50 UTC, JhLedesma approved these changes

2022-02-03 00:50 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +    }
A este tipo de clases se le llama "Utils" van en un paquete utils, la podrias llamar DateUtil a la clase

2022-02-03 00:50 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +            throw new BadRequestException("Error can't remove sim whit id: " + id);
Esta bueno especificar que el error es porque no existe

2022-02-03 00:50 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/config/ExceptionConfig.java
> +}
Quiero felicitarte por agregar un controller advice y no solo lanzar las excepciones. Es parte de un tp que te viene mas adelante

2022-02-03 01:09 UTC, AlessandroBarrionuevo commented on src/main/java/com/spring/com/tp/services/SimService.java
> +    }
domo arigatou

2022-02-03 01:09 UTC, AlessandroBarrionuevo commented on src/main/java/com/spring/com/tp/config/ExceptionConfig.java
> +}
domo arigatou

2022-02-03 01:13 UTC, AlessandroBarrionuevo commented on src/main/java/com/spring/com/tp/services/SimService.java
> +    }
A que jerarquia de paquetes va? es algo general o es algo especifico del service?

2022-02-03 18:04 UTC, merged