Parte 4 jpa, conexion a bdd y a h2. Sin docker y usando optional en a…
AlessandroBarrionuevo/SpringBootTp pull request #4
Opened 2022-02-12 00:48 UTC by AlessandroBarrionuevo

Conexion con bdd mysql sin docker en local
Se utilizo optional en algunos lados
Se dejo una base de datos en memoria h2

2022-02-12 01:42 UTC, JhLedesma requested changes

2022-02-12 01:42 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/model/Book.java
> +    public Book(String isbn, String title, String s, String publisher, String s1, String publishedDate) {
s1 no es un nombre descriptivo, s tampoco

2022-02-12 01:42 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/model/Sim.java
> +//https://www.youtube.com/watch?v=2fvUrpYG95w
??

2022-02-12 01:42 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
>      }
Usar getOrElseThrow no usar if.  Si se quiere hacer una accion como loguear en el medio de un optional investigar .peek si no, loguear despues

2022-02-12 01:42 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
>          }else{
Lo mismo que antes, no usar el if

2022-02-14 23:52 UTC, AlessandroBarrionuevo commented on src/main/java/com/spring/com/tp/model/Sim.java
> +//https://www.youtube.com/watch?v=2fvUrpYG95w
es el video que utilice para ver las relacionen de jpa.
como no estaba seguro si estaba bien, lo deje para que lo revises

2022-02-21 14:33 UTC, JhLedesma requested changes

2022-02-21 14:33 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/controller/SimController.java
> +        return ResponseEntity.ok("Sim Deleted");
Eliminaste el log de sim deleted, esta bien no repetir el mensaje y esta bien retornarlo en el response entity, pero que lo retornes en el response entity no hace que se loguee automaticamente. Y otra cosa que lo marcamos muchas veces, poner solo "Sim deleted" sin un id hace que se pierda en los logs cuando filtras por un id

2022-02-21 14:33 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/controller/SimController.java
> +        return ResponseEntity.ok("Sim Deleted");
Esta bien eliminar el log de sim deleted si es que esta en el sim service

2022-02-21 14:33 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        return Optional.ofNullable(sim.orElseThrow(() -> new NotFoundException("Sim not fund")));
fund?

2022-02-21 14:33 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        return simOldValue.orElseThrow(() -> new NotFoundException("Sim doesn't exist so you can't update them"));
update it no update them

2022-02-21 14:33 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        simToDelete.orElseThrow(() -> new BadRequestException("Error. can't remove sim id " + id + " because does not exist"));
Sim id cannot be removed because ....

2022-02-22 16:25 UTC, JhLedesma requested changes

2022-02-22 16:25 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/controller/SimController.java
>          log.info("Giving back Sim: {}", sim);
No tiene que responder optional,hay que usar .getOrlElse

2022-02-22 16:25 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/controller/SimController.java
> +        return ResponseEntity.ok("Sim Deleted");
No muestra el id, los dos mensajes tienen que mostrar el ID

2022-02-22 16:25 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/controller/dto/SimInput.java
> +    private Integer dni;
Los Dni tienen que ser string en muchos paises tienen letras

2022-04-28 19:55 UTC, JhLedesma requested changes

2022-04-28 19:55 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/BookService.java
>      public Book createBook(String isbn){
Si el metodo de un repo/service-repo dice Create o save, es importante que lo guarde en la base de datos, no solo que cree el objeto

2022-04-28 19:55 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        return simOldValue.orElseThrow(() -> new NotFoundException("Sim doesn't exist so you can't update it"));
Aca solamente estas llamando al findById. Si vos queres updatear, tenes que usar el metodo save. Es mas, en los services se suele tener un metodo create que llama al save del repo. Y ademas para el update tambien llamas al save del repo

2022-04-28 19:55 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        simToDelete.orElseThrow(() -> new BadRequestException("Error. Sim: "+ id + " could not deleted" ));
En ningun momento estas llamando al delete del repo. Para llamar al delete del repo no hace falta antes buscar por Id antes, directamente usa deleteById del repo. Si existe borra, si no, no borra nada

2022-04-28 19:55 UTC, JhLedesma commented on src/main/java/com/spring/com/tp/services/SimService.java
> +        simToDelete.orElseThrow(() -> new BadRequestException("Error. Sim: "+ id + " could not deleted" ));
Se ve claramente a la izquierda como borraste el metodo que tenias que llamar

2022-04-29 15:17 UTC, AlessandroBarrionuevo reviewed
en el update saque el optional, en el delete no debido a que la aplicacion se interrumpe si no lanzo la excepcion.

2022-05-16 13:53 UTC, merged